---
excludes:
  scopes:
  - pattern: "dev"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
  - pattern: "lint"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for static code analysis only."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
license_choices:
  repository_license_choices:
    - given: FTL OR GPL-2.0-or-later
      choice: FTL
resolutions:
  rule_violations:
    - message: ".*PyPI::numpy:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause license: https://github.com/numpy/numpy/blob/v2.2.1/LICENSES_bundled.txt"
    - message: ".*PyPI::pandas:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::jupyter-core:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::jupyter-client:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::prompt-toolkit:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::traitlets:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::matplotlib-inline:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::ipykernel:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::pyzmq:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::comm:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::packaging:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::python-dateutil:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::cycler:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::contourpy:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::kiwisolver:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::pillow:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::nbformat:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::scipy:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::referencing:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::scikit-learn:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::attrs:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Ignore license"
    - message: ".*PyPI::markupsafe:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ignore license"
    - message: ".*PyPI::jinja2:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ignore license"
    - message: ".*PyPI::seaborn:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ignore license"
    - message: ".*PyPI::odfpy:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ignore license"
    - message: ".*PyPI::typing-extensions:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ignore license"
    - message: ".*PyPI::click:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ignore license"
    - message: ".*PyPI::ipython-pygments-lexers:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ignore license"
    - message: ".*PyPI::jsonschema-specifications:.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ignore license"